core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',  include('users.urls')),
    path('',  include('questions.urls')), 
    path('',  include('answers.urls')), 
    path('accounts/', include('django.contrib.auth.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

answers/models.py
from django.db import models
from users.models import User
from questions.models import Question
from django.db.models.signals import post_save, post_delete
from ckeditor_uploader.fields import RichTextUploadingField


# Create your models here.

class Answer(models.Model):
      author = models.ForeignKey(User, on_delete=models.CASCADE)
      question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='comments')
      author_of_question = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, related_name='author_of_question')
      body = RichTextUploadingField()
      date_answered = models.DateTimeField(auto_now_add=True)
      likes = models.IntegerField(default=0)
      replies = models.IntegerField(default=0)
      is_seen = models.BooleanField(default=False)

      def __str__(self):
		      return str(self.body)

    
     
    

class Reply(models.Model):
      answer = models.ForeignKey(Answer, on_delete=models.CASCADE, related_name='replys'  )  
      author = models.ForeignKey(User, on_delete=models.CASCADE)
      author_of_answer = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, related_name='answer_owner') 
      body = models.TextField()
      date = models.DateTimeField(auto_now_add=True, null=True, blank=True)
      is_seen = models.BooleanField(default=False)

      def __str__(self):
		      return str(self.body)


class Likes(models.Model):
      author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_like')
      answer = models.ForeignKey(Answer  , on_delete=models.CASCADE, related_name='post_like')  
      author_of_answer = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, related_name='authoranswer')
      date = models.DateTimeField(auto_now_add=True)   
      is_seen = models.BooleanField(default=False)

      def __str__(self):
		      return str(self.answer)

      


questions/models.py
from email.mime import image
from django.db import models
from django.urls import reverse
from users.models import User
from ckeditor_uploader.fields import RichTextUploadingField

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField()

    def __str__(self):
        return self.name

class Question(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    title = models.CharField(max_length=255, blank=True, null=True)
    body = RichTextUploadingField( blank=True, null=True)
    slug = models.SlugField(blank=True, null=True)
    answers = models.PositiveIntegerField(default=0,  blank=True, null=True)
    date = models.DateTimeField(auto_now_add=True, blank=True, null=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('detail', args=[str(self.slug)])    




users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

from django.contrib.auth import get_user_model
from django.urls import reverse
# Create your models here.


class User(AbstractUser):
      phone_number = models.CharField(max_length=13, null=True, blank=True)
      pro = models.ForeignKey("questions.Category", on_delete=models.SET_NULL, null=True, blank=True )
      address = models.CharField(max_length=100, null=True, blank=True)
      bio = models.CharField(max_length=100, null=True, blank=True)
      pic = models.ImageField(upload_to='profiles/', blank=True, null=True)
      web = models.URLField(null=True, blank=True)
      github = models.URLField(null=True, blank=True)
      is_verified = models.BooleanField(default=False)

      def get_absolute_url(self):
        return reverse('home')
      
            



templates/answer_nots.html
{% extends 'base.html' %}

{% load static %}
{% load humanize %}

{% block content %}
<title>Notification | {{user.first_name}} {{user.last_name}} </title>
    
<br><br>
{% if answers %}
{% for answer in answers %}

<div class="container card border-secondary mb-3" style="max-width: 25rem;">
             
            
      <div class="card-body text-secondary">
            <small class="text-muted">{{ answer.date_answered|naturaltime }}</small>
        <h5 class="card-title"> <a style="text-decoration: none;" href="/profile/{{answer.author.username}}"  >
            <img
            {% if answer.author.pic %}
            src="{{answer.author.pic.url}}"
            {% else %}
            src="https://www.business2community.com/wp-content/uploads/2017/08/blank-profile-picture-973460_640.png"
            {% endif %}
            class="rounded-circle"
            height="35"
            alt="Black and White Portrait of a Man"
            loading="lazy" /><span style="font-size: 15px;" class="text-muted " > @{{answer.author.username}} </span></a><small style="color: black;" >answered to your <a href="{% url 'detail' answer.question.id answer.question.slug  %}" >question: </a></small></h5>
            <p style="overflow: hidden; text-overflow:ellipsis; display:-webkit-box; -webkit-line-clamp: 3; -webkit-box-orient: vertical;" class="card-text">{{answer.body|safe}}</p>
        
      </div>
    
</div> 
{% endfor %}
{% else %}
<br><br>
<center>Nobody answered to your question</center>  
{% endif %}
</div>
{% endblock %}

templates/askquestion.html
{% extends 'base.html' %}

{% block content %}
<title> Ask question | {{user.first_name}} {{user.last_name}} </title>
<br><br>
<script src="/static/ckeditor/ckeditor-init.js" data-ckeditor-basepath="/static/ckeditor/ckeditor/" id="ckeditor-init-script"></script>
<script src="/static/ckeditor/ckeditor/ckeditor.js"></script>
<form method='POST'    > 
{% csrf_token %}
<div class="container">
      

      <center>Ask question from community</center><br>
      <h6>Title of question</h6>
      <input required type="text" name="title"  placeholder="Title of your question"  maxlength="150" class="textinput textInput form-control" >
      <br>
      <h6>Select a category</h6>
      <select name="category" id="id_category">
           
            {% for cat in category %}
            <option value="{{cat.id}}" selected>{{cat.name}}</option>
            {% endfor %}
      </select><br><br>

      
      <h6>Body part</h6>
      <textarea  name="body" cols="80" rows="10" id="id_body" data-processed="0" data-config="{&quot;skin&quot;: &quot;moono-lisa&quot;, &quot;toolbar_Basic&quot;: [[&quot;Source&quot;, &quot;-&quot;, &quot;Bold&quot;, &quot;Italic&quot;]], &quot;toolbar_Full&quot;: [[&quot;Styles&quot;, &quot;Format&quot;, &quot;Bold&quot;, &quot;Italic&quot;, &quot;Underline&quot;,   &quot;Undo&quot;, &quot;Redo&quot;], [&quot;Link&quot;, &quot;Unlink&quot;], [&quot;Image&quot;, &quot;Table&quot;, &quot;HorizontalRule&quot;], [&quot;TextColor&quot;, &quot;BGColor&quot;], [ &quot;SpecialChar&quot;], [&quot;Source&quot;]], &quot;toolbar&quot;: &quot;full&quot;, &quot;height&quot;: 291, &quot;width&quot;: 835, &quot;filebrowserWindowWidth&quot;: 940, &quot;filebrowserWindowHeight&quot;: 725, &quot;extraPlugins&quot;: &quot;codesnippet&quot;, &quot;filebrowserUploadUrl&quot;: &quot;/ckeditor/upload/&quot;, &quot;filebrowserBrowseUrl&quot;: &quot;/ckeditor/browse/&quot;, &quot;language&quot;: &quot;en-us&quot;}" data-external-plugin-resources="[]" data-id="id_body" data-type="ckeditortype"></textarea>
      <br><button  type="submit" class="btn btn-outline-primary" >Ask question</button>

</div>


  
</form>

{% endblock content %}

templates/detail.html
{% extends 'base.html' %}
{% load hitcount_tags %}
{% block content %}
<title>Detail| {{object.title}}</title>
<div class="container" >
      <script src="/static/ckeditor/ckeditor-init.js" data-ckeditor-basepath="/static/ckeditor/ckeditor/" id="ckeditor-init-script"></script>
      <script src="/static/ckeditor/ckeditor/ckeditor.js"></script>
      <div >
            <br><br>                
            <div style="float: left; width: 69%; " >
                  <h4>{{ object.title }}</h4>
                  <p>{{object.body|safe}}</p>
                  <br>
                  <p style="float: right; color: rgb(127, 127, 127); " > <a href="/profile/{{  object.author.username }}">  @{{object.author.username}} </a> | {{object.date}} | {{hits}} </p>
                  <div style="clear:both ;"></div><hr>
                  <div class="answers">
                        <div  style="clear:both ;"></div>
                        <h4 style="float: left; width: 70%;" > Here is some answers.</h4>
                       
                        <br>
                        <div style="clear:both ;"></div>
                        {% for answer in answers  %}
                        <div id="{{answer.id}}" >
                              <div style="   float: left; width:10%"  class=" container staff">
                                    <a style="text-decoration: none; color:black " href="{% url 'postlike' answer.id %}"><i style="margin-top:70px" class="fa-solid fa-circle-check  "></i></a>
                                    <h5 class="text-muted" >{{ answer.likes }}</h6>
                              </div>
                              <div id="comments" style="float: right; width:85%" class="ans ">
                                    <p>{{answer.body|safe}}</p>
                                    <footer ><small style="float:right"   class="blockquote-footer" ><a href="/profile/{{  answer.author.username }}" >@{{answer.author }} </a> | {{answer.date_answered}} </small></footer>
                                    <hr>
                                    <h6 class="text-muted" > Comments </h6>
                                    {%  for comment in answer.replys.all %}
                                    <div id="{{comment.id}}" class="">
                                          <small>{{  comment.body }}</small>
                                          <footer ><small style="float:right"   class="blockquote-footer" ><a href="/profile/{{  comment.author }}" >@{{comment.author }} </a> | {{comment.date}} </small></footer> 
                                          <div style="clear: both;"><hr></div>
                                    </div>
                                    {% endfor %}
                                    {% if user.is_authenticated %} 
                                    <form method="post" action="{{object.slug}}"  class="d-flex">
                                          {% csrf_token %}
                                          <input required name="bodycomment" style="border: none; float: left;  " placeholder="add a comment" >
                                          <input required name="answer_id" style="height: 0px;"  class="form-control me-2 invisible " value="{{answer.id}}"  placeholder="Commentbody" aria-label="body">
                                          <button  type="submit"    class="badge btn-dark" style="  float:right"  >Send</button>
                                          <div style="clear: both;"></div><br>      
                                    </form>
                                    {% else %}
                                    <br>
                                    <code>Please login to add comment</code>
                                   
                                    {% endif %}

                              </div>
                        </div>   
                        <div style="clear: both;" ></div><hr>
                        {% endfor %} 
                        {% if user.is_authenticated %} 
                        <form method="post" action="{{object.slug}}"  class="d-flex">
                              {% csrf_token %}
                              <textarea  name="body" cols="40" rows="10" id="id_body" data-processed="0" data-config="{&quot;skin&quot;: &quot;moono-lisa&quot;, &quot;toolbar_Basic&quot;: [[&quot;Source&quot;, &quot;-&quot;, &quot;Bold&quot;, &quot;Italic&quot;]], &quot;toolbar_Full&quot;: [[&quot;Styles&quot;, &quot;Format&quot;, &quot;Bold&quot;, &quot;Italic&quot;, &quot;Underline&quot;,   &quot;Undo&quot;, &quot;Redo&quot;], [&quot;Link&quot;, &quot;Unlink&quot;], [&quot;Image&quot;, &quot;Table&quot;, &quot;HorizontalRule&quot;], [&quot;TextColor&quot;, &quot;BGColor&quot;], [ &quot;SpecialChar&quot;], [&quot;Source&quot;]], &quot;toolbar&quot;: &quot;full&quot;, &quot;height&quot;: 291, &quot;width&quot;: 835, &quot;filebrowserWindowWidth&quot;: 940, &quot;filebrowserWindowHeight&quot;: 725, &quot;extraPlugins&quot;: &quot;codesnippet&quot;, &quot;filebrowserUploadUrl&quot;: &quot;/ckeditor/upload/&quot;, &quot;filebrowserBrowseUrl&quot;: &quot;/ckeditor/browse/&quot;, &quot;language&quot;: &quot;en-us&quot;}" data-external-plugin-resources="[]" data-id="id_body" data-type="ckeditortype"></textarea>
                             
                              <button class="btn btn-outline-dark" type="submit">Answer</button>
                        </form>
                        {% else %}
                        <br>
                        <code>Please login to give solution to this answer</code>
                        <a style="margin-right:5px;" href="/login" class="btn btn-primary" >Login </a>
                        <a href="/signup" class="btn btn-primary" > Signup</a>
                        {% endif %}
                  </div>
                  <div style="clear:both ;"></div><br>
                  
            </div>
              
  
      </div>              
            <div style="float: right; width: 29%;  " >
            <div class="card-body">
                  <h4 class="d-flex align-items-center mb-3"> Related questions</h4>
                  {% for r in related_questions %}
                  <div >
                        <small>{{r.title}}</small>
                        <p class=><small><small><i class="fa-solid fa-handshake-angle"></i>{{r.answers}} |  
                        <i class="fa-solid fa-eye"></i> {% get_hit_count for r %}   </small></small></p>
                        <hr>
                  </div>
                  {% endfor %}
                    
                 
                    
            </div>
            </div>              
            
      
      <div style="clear:both ;"></div>
      <br><br><br><br>
   
</div>
  
{% endblock content %}

templates/edit-profile.html

{% extends 'base.html' %}
{% load hitcount_tags %}
{% block content %}
<title>Edit | {{user.first_name}} {{user.last_name}} </title>
{% load crispy_forms_tags %}


<br><br>
<div class="container">
<h4><center>In this form you can  change your personal information</center></h4>{{users}}
{%  if object %}

 <form enctype="multipart/form-data"  class="container" method="post">
   {% csrf_token  %}
  <div class="main-body">
            
                  
                  
            
    <div class="row gutters-sm">
      <div class="col-md-4 mb-3">
        <div class="card">
          <div class="card-body">
            <div class="d-flex flex-column align-items-center text-center">
              {% if user.pic %}
              <img src="{{user.pic.url}}" alt="{{user.pic.url}}" class="rounded-circle" width="150">
              {% else %}
              <img src="https://www.business2community.com/wp-content/uploads/2017/08/blank-profile-picture-973460_640.png" alt="guest" class="rounded-circle" width="150">
              {% endif %}
              <label for="pic-clear_id">Clear pic:  <input type="checkbox" name="pic-clear" id="pic-clear_id"> </label>
              <input type="file" name="pic" accept="image/*" class="clearablefileinput form-control-file" id="id_pic">
              <div class="mt-3">
                <h4>{{user.first_name}} {{user.last_name}}</h4>
                
          
                 <p style="margin-top: 10px;" class="text-secondary mb-1">{{user.bio}}</p>
                <p class="text-muted font-size-sm">{{user.address}}</p>
                
              </div>
            </div>
          </div>
        </div>
        <div class="card mt-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
              <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-globe mr-2 icon-inline"><circle cx="12" cy="12" r="10"></circle><line x1="2" y1="12" x2="22" y2="12"></line><path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"></path></svg>Website</h6>
              <span class="text-secondary"><input  type="url"  {% if user.web %} value="{{user.web}}" {% endif %} name="web" maxlength="200" ></span>
            </li>
          
            
            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
              <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-github mr-2 icon-inline"><path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path></svg>Github</h6>
              <span class="text-secondary"><input  type="url" {% if user.github %} value="{{user.github}}" {% endif %} name="github" maxlength="200" ></span>
            </li>
           
            
          </ul>
        </div>
      </div>
      <div class="col-md-8">
        <div class="card mb-3">
          <div class="card-body">
            <div class="row">
              <div class="col-sm-3">
                <h6 class="mb-0">First Name</h6>
              </div>
              <div class="col-sm-9 text-secondary">
                
                <input required type="text" name="first_name" value="{{user.first_name}}" maxlength="150" class="textinput textInput form-control" id="id_first_name">
              </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-sm-3">
                  <h6 class="mb-0">LastName</h6>
                </div>
                <div class="col-sm-9 text-secondary">
                      <input type="text" name="last_name" value="{{user.last_name}}" maxlength="150" class="textinput textInput form-control" id="id_first_name">
                </div>
              </div>
              <hr>
            <div class="row">
              <div class="col-sm-3">
                <h6 class="mb-0">Username</h6>
              </div>
              <div class="col-sm-9 text-secondary">
                <input required type="text" name="username" value="{{user.username}} " maxlength="150" class="textinput textInput form-control" required id="id_username">
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <h6 class="mb-0">Email</h6>
              </div>
              <div class="col-sm-9 text-secondary">
                {{user.email}} 
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <h6 class="mb-0">Phone</h6>
              </div>
              <div class="col-sm-9 text-secondary">
                
                <input type="text" name="phone_number" value="{{user.phone_number}}" maxlength="13" class="textinput textInput form-control" id="id_first_name"> 
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <h6 class="mb-0">Bio</h6>
              </div>
              <div class="col-sm-9 text-secondary">
                 
                <input type="text" name="bio" value="{{user.bio}}" maxlength="100" class="textinput textInput form-control" id="id_bio">
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <h6 class="mb-0">Address</h6>
              </div>
              <div class="col-sm-9 text-secondary">
                
                <input type="text" name="address" value="{{user.address}} " maxlength="100" class="textinput textInput form-control" id="id_address">
              </div>
              
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <h6 class="mb-0"> Pro:</h6>
              </div>
              <div class="col-sm-9 text-secondary">
                
                <select name="pro" id="id_pro">
                  <option value="" selected>---------</option>
                {% for c  in category %}
                  <option value="{{c.id}}">{{c.name}}</option>
                {% endfor %}
                  
                
                </select><br><br>
              </div>
              
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-12">
                <button type="submit" class="btn btn-primary"  >Save Changes</button>
              </div>
            </div>
            
            
          </div>
       </div>

      </div>
    </div>

  </div>    
            
      

</form>

{% else %} 
<center>You are not owner</center>

    
  {% endif   %}  
</div>
{% endblock content %}

templates/test.html
{% load crispy_forms_tags %}
{% load static %}

<from method="post">
     
            
      {% csrf_token %}
      {{form.media}}
      {{ form|crispy }}
            <button type="submit" class="btn btn-outline-dark" >Create</button>
        </form>
</from>


{% extends 'base.html' %}
{% load hitcount_tags %}
{% block content %}

<div>
      <br><br>
      <div class="container">
            <form method="post" action="/">{% csrf_token %}
            <div class="main-body">
            
                  
                  
            
                  <div class="row gutters-sm">
                    <div class="col-md-4 mb-3">
                      <div class="card">
                        <div class="card-body">
                          <div class="d-flex flex-column align-items-center text-center">
                            <img src="{{user.pic.url}}" alt="{{user.pic.url}}" class="rounded-circle" width="150">
                           
                            <label for="pic-clear_id">Clear pic:  <input type="checkbox" name="pic-clear" id="pic-clear_id"> </label>
                            <input type="file" name="pic" accept="image/*" class="clearablefileinput form-control-file" id="id_pic">
                            <div class="mt-3">
                              <h4>{{user.first_name}} {{user.last_name}}</h4>
                              
                        
                               <p style="margin-top: 10px;" class="text-secondary mb-1">{{user.bio}}</p>
                              <p class="text-muted font-size-sm">{{user.address}}</p>
                              
                            </div>
                          </div>
                        </div>
                      </div>
                      <div class="card mt-3">
                        <ul class="list-group list-group-flush">
                          <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                            <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-globe mr-2 icon-inline"><circle cx="12" cy="12" r="10"></circle><line x1="2" y1="12" x2="22" y2="12"></line><path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"></path></svg>Website</h6>
                            <span class="text-secondary"><input  type="url" value="{{user.web}}" name="web" maxlength="200" ></span>
                          </li>
                          <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                            <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-github mr-2 icon-inline"><path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path></svg>Github</h6>
                            <span class="text-secondary"><input  type="url" value="{{user.github}}" name="github" maxlength="200" ></span>
                          </li>
                         
                          
                        </ul>
                      </div>
                    </div>
                    <div class="col-md-8">
                      <div class="card mb-3">
                        <div class="card-body">
                          <div class="row">
                            <div class="col-sm-3">
                              <h6 class="mb-0">First Name</h6>
                            </div>
                            <div class="col-sm-9 text-secondary">
                              
                              <input type="text" name="first_name" value="{{user.first_name}}" maxlength="150" class="textinput textInput form-control" id="id_first_name">
                            </div>
                          </div>
                          <hr>
                          <div class="row">
                              <div class="col-sm-3">
                                <h6 class="mb-0">LastName</h6>
                              </div>
                              <div class="col-sm-9 text-secondary">
                                    <input type="text" name="last_name" value="{{user.last_name}}" maxlength="150" class="textinput textInput form-control" id="id_first_name">
                              </div>
                            </div>
                            <hr>
                          <div class="row">
                            <div class="col-sm-3">
                              <h6 class="mb-0">Username</h6>
                            </div>
                            <div class="col-sm-9 text-secondary">
                              <input type="text" name="username" value="{{user.username}} " maxlength="150" class="textinput textInput form-control" required id="id_username">
                            </div>
                          </div>
                          <hr>
                          <div class="row">
                            <div class="col-sm-3">
                              <h6 class="mb-0">Email</h6>
                            </div>
                            <div class="col-sm-9 text-secondary">
                              {{user.email}} 
                            </div>
                          </div>
                          <hr>
                          <div class="row">
                            <div class="col-sm-3">
                              <h6 class="mb-0">Phone</h6>
                            </div>
                            <div class="col-sm-9 text-secondary">
                              
                              <input type="text" name="phone_number" value="{{user.phone_number}}" maxlength="13" class="textinput textInput form-control" id="id_first_name"> 
                            </div>
                          </div>
                          <hr>
                          <div class="row">
                            <div class="col-sm-3">
                              <h6 class="mb-0">Bio</h6>
                            </div>
                            <div class="col-sm-9 text-secondary">
                               
                              <input type="text" name="bio" value="{{user.bio}}" maxlength="100" class="textinput textInput form-control" id="id_bio">
                            </div>
                          </div>
                          <hr>
                          <div class="row">
                            <div class="col-sm-3">
                              <h6 class="mb-0">Address</h6>
                            </div>
                            <div class="col-sm-9 text-secondary">
                              
                              <input type="text" name="address" value="{{user.address}} " maxlength="100" class="textinput textInput form-control" id="id_address">
                            </div>
                          </div>
                          <hr>
                          <div class="row">
                            <div class="col-sm-12">
                              <button type="submit" class="btn btn-primary"  >Save Changes</button>
                            </div>
                          </div>
                          
                          
                        </div>
                     </div>
        
                    </div>
                  </div>
        
                </div>
                </form>
            </div>
      </div>
    
    



{% endblock content %}











<form  class="container" method="post">
     
            
  {% csrf_token %}
 
  {{ form|crispy }}
        <button type="submit" class="btn btn-outline-dark" >Create</button>
</form>